name: Deploy to GitHub Pages

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install dependencies
      - run: npm ci

      # Build the project (add --base if needed!)
      - run: |
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
